apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:    
    name: istio-system
    # istio-injection: enabled

apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:    
    name: default
    istio-injection: enabled