apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: productpage
spec:
  hosts:
  - productpage
  http:
  - route:
    - destination:
        host: productpage
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
  - reviews
  http:
  ###
  # And even better, the same exact primitives can be used to simulate failures.
  # - fault:
  #     abort:
  #       httpStatus: 503
  #       percent: 25
  #   # match:
  #   # - headers:
  #   #     end-user:
  #   #       exact: travis
  #   route:
  #   - destination:
  #       host: reviews
  #       subset: v1
  ###
  # Or delays.
  # - fault:
  #     delay:
  #       fixedDelay: 5s
  #       percent: 100
  #   route:
  #   - destination:
  #       host: reviews
  #       subset: v3
  ###
  # This traffic routing rule enables a different version of the reviews backend app to be served to a very special user.
  # - match:
  #   - headers:
  #       end-user:
  #         exact: tomstchief
  #   route:
  #   - destination:
  #       host: reviews
  #       subset: v2  
  - route:
    - destination:
        host: reviews
        subset: v1
  ###
  # Even better, this traffic routing rule is to simulate canary deployments. Only about 20% of the traffic will be routed to v3.
  #     weight: 60
  #   - destination:
  #       host: reviews
  #       subset: v2
  #     weight: 20
  #   - destination:
  #       host: reviews
  #       subset: v3
  #     weight: 20
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ratings
spec:
  hosts:
  - ratings
  http:
  - route:
    - destination:
        host: ratings
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: details
spec:
  hosts:
  - details
  http:
  - route:
    - destination:
        host: details
        subset: v1
---